// Copyright 2026 LiteProcManager Authors. All rights reserved.

#ifndef LITE_PROC_MANAGER_LANGUAGE_MANAGER_H_
#define LITE_PROC_MANAGER_LANGUAGE_MANAGER_H_

#include <windows.h>
#include <string>
#include <unordered_map>

#include "app_settings.h"

namespace lite_proc_manager {

enum class StringId {
  kAppTitle,
  kSearchPlaceholder,
  kLabelSearch,
  kLabelInterval,
  kIntervalPause,
  kStatusProcesses,
  kStatusThreads,
  kStatusHandles,
  kStatusCpu,
  kStatusMemory,
  kStatusCommit,
  // Menu & Toolbar
  kMenuFile,
  kMenuView,
  kMenuOptions,
  kMenuMonitorRules,
  kMenuSelectColumns,
  kMenuAlwaysOnTop,
  kMenuToggleTheme,
  kMenuExit,
  kMenuOpen,
  kMenuRefreshNow,
  kMenuEndProcess,
  kMenuOpenLocation,
  kMenuOnlineSearch,
  kMenuProperties,
  kMenuSetPriority,
  kMenuRestartAsAdmin,
  kMenuCopyJson,
  kMenuCopyTsv,
  kMenuHelp,
  kMenuAbout,
  kAboutTitle,
  kAboutAppName,
  // Tooltips
  kTooltipThemeLight,
  kTooltipThemeDark,
  kTooltipRefresh,
  kTooltipOptions,
  kTooltipMonitor,
  kTooltipColumns,
  kTooltipAlwaysOnTop,
  kTooltipViewTree,
  kTooltipViewList,
  kTooltipTopmostOff,
  kTooltipTopmostOn,
  kTooltipEndProcess,
  kTooltipQuickFilter,
  kTooltipInterval,
  kTooltipRestartAdmin,
  kTooltipRunningAsAdmin,
  // Dialog Common
  kBtnOk,
  kBtnCancel,
  kBtnSave,
  kBtnAdd,
  kBtnEdit,
  kBtnDelete,
  kBtnRemove,
  kBtnToggle,
  kBtnMoveUp,
  kBtnMoveDown,
  kBtnDefault,
  kBtnTestWarn,
  kBtnTestErr,
  kConfirmDelete,
  kConfirmDeleteMultiple,
  kConfirmRestartTheme,
  kRestartNoticeTitle,
  kMsgConfirmExit,
  // Options Dialog
  kDlgOptionsTitle,
  kLabelLanguage,
  kLabelTheme,
  kLabelListFont,
  kLabelUiFont,
  kLabelFont,
  kBtnChangeFont,
  kLabelRefreshInterval,
  kLabelAlwaysOnTop,
  kLabelMinimizeToTray,
  kLabelAutoStart,
  kLangAuto,
  kLangJapanese,
  kLangEnglish,
  kThemeLight,
  kThemeDark,
  kSecondsUnit,
  kLabelExcludedProcesses,
  kDlgAddExcludedTitle,
  kLabelAddExcludedPrompt,
  // Monitor Dialog
  kDlgMonitorTitle,
  kColStatus,
  kColRuleName,
  kColLevel,
  kColTarget,
  kColCondition,
  kStatusEnabled,
  kStatusDisabled,
  kLevelWarning,
  kLevelCritical,
  kMatchExact,
  kMatchContains,
  kMatchStartsWith,
  kMatchEndsWith,
  kMatchTargetProcessName,
  kMatchTargetPid,
  kRuleEditTitleAdd,
  kRuleEditTitleEdit,
  kRuleNameLabel,
  kTargetTypeLabel,
  kMatchTypeLabel,
  kPatternLabel,
  kConditionLabel,
  kCooldownLabel,
  kUnitSecondsCooldown,
  kLogicAnd,
  kLogicOr,
  kLabelRuleName,
  kLabelTarget,
  kLabelLevel,
  kLabelLogic,
  kOpContains,
  kItemDefault,
  kMsgRuleNameEmpty,
  kMsgPatternEmpty,
  kMsgSelectRuleToEdit,
  kMsgSelectRuleToDelete,
  kMsgSelectRuleToToggle,
  kLabelNotifyIfNotFound,
  kMsgProcessNotFound,
  // Column Selector Dialog
  kDlgColumnSelectorTitle,
  kSelectColumnsInstruction,
  kBtnSelectAll,
  kBtnDeselectAll,
  // Priority Names
  kPriorityRealtime,
  kPriorityHigh,
  kPriorityAboveNormal,
  kPriorityNormal,
  kPriorityBelowNormal,
  kPriorityLow,
  // Process Details & Snapshot Status
  kStatusRunning,
  kStatusSuspended,
  kYes,
  kNo,
  kEnabled,
  kDisabled,
  kEnabledPermanent,
  kNotApplicable,
  kPlatform32Bit,
  kPlatform64Bit,
  kPropertiesTitlePrefix,
  kPropertiesHeader,
  kPropImageName,
  kPropPid,
  kPropParentPid,
  kPropStatus,
  kPropUser,
  kPropDescription,
  kPropArchitecture,
  kPropPriority,
  kPropThreads,
  kPropHandles,
  kPropCpu,
  kPropWorkingSet,
  kPropCommit,
  kPropStartTime,
  kPropFilePath,
  // Menus & Copy
  kMenuCopy,
  kMenuCopyCommandLine,
  kMenuCopyPath,
  kMenuEndProcessTree,
  // Message Boxes & Prompts
  kMsgConfirmEndProcess,
  kMsgConfirmEndProcessMultiple,
  kTitleConfirmEndProcess,
  kMsgEndProcessError,
  kTitleError,
  kMsgConfirmEndTree,
  kTitleConfirmEndTree,
  kMsgEndTreePartial,
  kTitleNotice,
  kTitleInfo,
  kMsgWarnRealtime,
  kTitleChangePriority,
  kMsgChangePriorityError,
  kMsgAccessDenied,
  kMsgFileNotFound,
  kMsgRealtimeWarning,
  kMsgTrayMinimized,
  kMsgError,
  kMsgInfo,
  kMsgWarning,
  // Services Management
  kTabProcesses,
  kTabServices,
  kSvcColName,
  kSvcColDisplayName,
  kSvcColPid,
  kSvcColState,
  kSvcColStartType,
  kSvcColAccount,
  kSvcColDescription,
  kServiceStateRunning,
  kServiceStateStopped,
  kServiceStateStartPending,
  kServiceStateStopPending,
  kServiceStatePaused,
  kServiceStatePausePending,
  kServiceStateContinuePending,
  kServiceStateUnknown,
  kServiceStartTypeAuto,
  kServiceStartTypeManual,
  kServiceStartTypeDisabled,
  kServiceStartTypeBoot,
  kServiceStartTypeSystem,
  kServiceStartTypeUnknown,
  kMenuServiceStart,
  kMenuServiceStop,
  kMenuServiceRestart,
  kMenuServiceStartup,
  kMenuServiceGoToProcess,
  kMenuProcessGoToService,
  kStatusServiceCounts,
};

class LanguageManager {
 public:
  static void Initialize(AppLanguage lang = AppLanguage::kAuto);
  static void SetLanguage(AppLanguage lang);
  static AppLanguage GetConfiguredLanguage();
  static bool IsJapanese();

  static const wchar_t* GetString(StringId id);
  static std::wstring GetColumnHeaderText(ProcessColumnId id);

 private:
  static void UpdateActiveLanguage();
};

}  // namespace lite_proc_manager

#endif  // LITE_PROC_MANAGER_LANGUAGE_MANAGER_H_
